### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by binary64** [designsecurity/progpilot#23]
```
PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /home/user/.static-analysis/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Op.php:96
Stack trace:
#0 /home/user/.static-analysis/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Op.php(96): is_array()
#1 /home/user/.static-analysis/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Op/Phi.php(28): PHPCfg\Op->addWriteRef()
#2 /home/user/.static-analysis/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Parser.php(1589): PHPCfg\Op\Phi->__construct()
#3 /home/user/.static-analysis/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Parser.php(1573): PHPCfg\Parser->readVariableRecursive()
#4 /home/user/.static-analysis/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Parser.php(1586): PHPCfg\Parser->readVariableName()
#5 /home/user/.static-analysis/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Parser.php(1573): PHPCfg\Parser->readVariableRecursive()
#6 /home/user/.static-analysis/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Parser.php(1598): PHPCfg\Parser-> in /home/user/.static-analysis/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Op.php on line 96
```

Is it possible to bump the dependency you use (ircmaxell/php-cfg) to the latest version? I think that might solve this..

**Comment by eric-therond** [comment]
Hi
what version of progpilot are you using? Did you try the latest 0.8.0?
If it not solve your problem, you can open an issue on https://github.com/ircmaxell/php-cfg/issues

Eric

**Comment by eric-therond** [comment]
if you have time to try with the latest progpilot version (v1.0.0)

Eric

**Comment by eric-therond** [comment]
progpilot version (v1.0.2) solves this.
