### ISSUE TITLE
Improvement: PHP 8 compatibility

### ISSUE THREAD

**Issue by Yivan** [designsecurity/progpilot#30]
Hello,

Having some PHP 8 project, this great tool is no more compatible (need "php": ">=7.2.5", and as well front my test "php": "< 8.0.0", **maybe progpilot composer.json file should be updated**).

**Is it planned to make it PHP 8 working (as PHP 8 is released since november 2020) ?**
It would be really great so it can be used in PHP 8 project!

Error returned in PHP 8:

```
PHP Fatal error:  Uncaught TypeError: PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned in phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:327
Stack trace:
#0 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(208): PhpParser\Lexer->getNextToken()
#1 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(158): PhpParser\ParserAbstract->doParse()
#2 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse()
#3 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse()
#4 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/ircmaxell/php-cfg/lib/PHPCfg/Parser.php(76): PhpParser\Parser\Multiple->parse()
#5 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/progpilot/package/src/progpilot/Analyzer.php(75): PHPCfg\Parser->parse()
#6 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/progpilot/package/src/progpilot/Analyzer.php(209): progpilot\Analyzer->parsePhp()
#7 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/progpilot/package/src/progpilot/Analyzer.php(294): progpilot\Analyzer->runInternalPhp()
#8 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/progpilot/package/src/progpilot/Analyzer.php(399): progpilot\Analyzer->runAllInternal()
#9 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/progpilot/package/src/progpilot/Command/ProgpilotCommand.php(61): progpilot\Analyzer->run()
#10 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/symfony/console/Command/Command.php(264): progpilot\Command\ProgpilotCommand->execute()
#11 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/symfony/console/Application.php(869): Symfony\Component\Console\Command\Command->run()
#12 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand()
#13 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun()
#14 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/progpilot/package/src/progpilot/Console/Application.php(32): Symfony\Component\Console\Application->run()
#15 phar:///var/www/html/git-excluded/ci/security/progpilot.phar/progpilot(19): progpilot\Console\Application->run()
#16 /var/www/html/git-excluded/ci/security/progpilot.phar(12): require('...')
#17 {main}
  thrown in phar:///var/www/html/git-excluded/ci/security/progpilot.phar/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 327
```

Thanks,
Best regards.

**Comment by LTSCommerce** [comment]
wish I'd seen this issue earlier!

**Comment by shayneoneill** [comment]
Is there a fix for this?

**Comment by shayneoneill** [comment]
bump :(

**Comment by eric-therond** [comment]
if you have time to try with the latest progpilot version (v1.0.0)

Eric

**Comment by eric-therond** [comment]
progpilot version (v1.0.2) solves this.
